詳細設計書(在庫一覧画面)作成
HarukaMatano/digital-ojt-development-cause-DroneInventorySystem pull request #15
Opened 2024-11-14 07:46 UTC by HarukaMatano

## 概要

詳細設計書の作成

## 実装方針・詳細

以下の機能を実装する為の詳細設計書を作成する。

■機能要件
●在庫一覧表示
在庫データを表形式で一覧表示する。（初期表示は全件を表示）
●検索機能
分類名、在庫名、在庫数を条件に検索できる。
検索結果は即座に反映され、一覧表示が更新される。

また、以下の非機能要件も実装する。

■非機能要件
●入力チェック：検索条件の項目は、不正文字列などのバリデーションを行うこと
●レスポンス速度：検索後、結果が2秒以内に表示されること
●データフォーマット：CSV形式での出力
●ログ管理：操作は全てログに記録し、追跡可能であること
●セキュリティ：権限のあるユーザーのみが在庫データにアクセス可能であること

## 影響範囲

詳細設計書の為、アプリケーション自体には影響なし。

## ファイル名
詳細設計書_在庫一覧画面.xlsx
共通設計書_ログ.xlsx

2024-11-15 06:16 UTC, aoyagi96 requested changes
- 参照するテーブル等共通部分も多いので、在庫一覧画面で1bookにして、各機能でシートを分ける方が可視性やメンテナンス性があがるかと思います。
共通部分はまとめる感じにしましょう。
- この設計書をもとに俣野さん以外の人が開発できるかをイメージしてみると良いかと思います。

2024-11-15 06:16 UTC, aoyagi96 commented on docs/詳細設計書/詳細設計書_在庫一覧画面_在庫一覧表示.xlsx
- ログの詳細な設計は別途まとる感じでしょうか？
出力先、フォーマット、ログレベルなど
https://qiita.com/tadashiro_ninomiya/items/19c774898c68add6185e

> 在庫情報テーブル、分類情報テーブル、在庫センター情報テーブルより項目を取得

何をキーに取得するかなど、もう少し詳しく書いた方が良いですね。

2024-11-15 06:16 UTC, aoyagi96 commented on docs/詳細設計書/詳細設計書_在庫一覧画面_データ出力機能.xlsx
- データ出力についてはもう少し具体的な実装方法を記載しておいた方が良いですね。
（これを見て俣野さん以外の人が実装できるかどうか。）
（例）
・検索結果のlistをjaksonライブライでcsv変換する
・デフォルトのファイル名はXXXXXX.csvとする
など

- CSVのフォーマット（サンプル）は記載しておきましょう。

2024-11-15 06:19 UTC, aoyagi96 commented on docs/詳細設計書/詳細設計書_在庫一覧画面_検索機能.xlsx
フローの記載はとても良いですね！
わかりやすいです。
フローとしてシートを分けても良いかもしれません、

2024-11-18 13:27 UTC, aoyagi96 requested changes
遅くなり申し訳ございません。
コメントしましたので、ご確認ください。

2024-11-18 13:27 UTC, aoyagi96 commented on docs/【DIGITAL OJT】WBS.xlsx
- nitsですが、タスク1、タスク2の表記は不要で良いかと思います
タスク1:表示項目の追加　→　表示項目の追加
- 今回成果物が詳細設計書、ソースコード、試験項目書兼結果報告書になるかと思いますが、それぞれ成果物がいつ完成するかも記載をお願いします。

2024-11-18 13:27 UTC, aoyagi96 commented on docs/詳細設計書/●詳細設計書_在庫一覧画面.xlsx
【処理詳細シート】
１．初期表示
　もう少し具体的に書いてください。
　（例）分類は在庫情報テーブルの分類IDをキーに、分類情報テーブルの名前を取得して表示する
　ＳＱＬを記載頂いてもＯＫです。

２．セキュリティ
　3.1　権限のあるユーザーのみが在庫データにアクセス可能である　→　3.1ではなく2.1かと
　もう少し具体的に書いてください。
　（例）admin_infoに登録されたユーザで、ID/PWで認証済みのユーザのみアクセス可能とする

３．１と同様にもう少し具体的に記載をお願いします。
　（例）複数条件で検索した場合、検索はANDでしょうか？　ORでしょうか？
　　　　名称は部分一致でしょうか、完全一致でしょうか？

【ログ詳細シート】
ログ管理は他の機能でも使う事になると思いますので、共通処理として詳細設計書を作成してください。

2024-11-18 23:57 UTC, HarukaMatano commented on docs/【DIGITAL OJT】WBS.xlsx
タスク表記を削除の上、詳細設計書、ソースコード、試験項目書兼結果報告書の完成予定を記載しました。尚、詳細設計書やソースコード、試験項目書兼結果報告書は画面ごとに分割しております。

2024-11-19 00:34 UTC, HarukaMatano commented on docs/詳細設計書/●詳細設計書_在庫一覧画面.xlsx
1.初期表示
取得方法の詳細明記、取得条件の変更

2.セキュリティ
セキュリティ内容の具体的な明記

3.検索ボタン
複数条件時の明記
部分一致完全一致の明記

4.ログ詳細シート
共通設計書_ログ.xlsxとして分割。

以上の4点を修正しました。

2024-11-19 04:01 UTC, aoyagi96 requested changes
大分良くなりました！
細かい指摘が多くて恐縮ですが、ご確認ください。

2024-11-19 04:01 UTC, aoyagi96 commented on docs/【DIGITAL OJT】WBS.xlsx
修正確認できました。
ご対応ありがとうございます！

2024-11-19 04:01 UTC, aoyagi96 commented on docs/詳細設計書/●詳細設計書_在庫一覧画面.xlsx
処理内容が具体的に書かれているので、すごく良くなったと思います。
細かくて恐縮ですが、以下の対応をお願いします。
- 初期表示のデータの並びは何の昇順、または降順か記載
- 検索処理ですが、バリデーションチェック等の詳細はフローに書かれてると思いますので、そちらを参照するような記載があった方が良いと思います。
- 検索結果の表示内容も詳細があった方が良いです。（初期表示と同じであればそれを参照するような記載）
- ログ管理
　「操作内容はログとして出力する。（ログ出力の詳細は共通資料参照）」
　のような書き方が良いかと思います。

2024-11-19 04:01 UTC, aoyagi96 commented on docs/詳細設計書/●共通設計書_ログ.xlsx
処理対象、処理内容、処理結果はログにオンコードでしょうか？
あるいはConstかDBから取得でしょうか？

2024-11-19 04:17 UTC, HarukaMatano commented on docs/詳細設計書/●詳細設計書_在庫一覧画面.xlsx
データの並びを初期表示に記載しました。
また、検索処理と検索結果の表示については参照先を明記しました。
ログ管理の記載を指示していただいた形に変更しました。

2024-11-19 04:23 UTC, HarukaMatano commented on docs/詳細設計書/●共通設計書_ログ.xlsx
ログにオンコードと追記しました。

2024-11-19 05:17 UTC, aoyagi96 requested changes
すいません、少し修正をお願いします。

2024-11-19 05:17 UTC, aoyagi96 commented on docs/詳細設計書/●詳細設計書_在庫一覧画面.xlsx
- 並び順ですが、在庫センター情報ではなく、在庫情報かと。

2024-11-19 05:17 UTC, aoyagi96 commented on docs/詳細設計書/●共通設計書_ログ.xlsx
すいません、意図が伝わってませんでした。
処理対象の画面名とかは、constから取得した方が良いかと思います。

2024-11-19 05:19 UTC, HarukaMatano commented on docs/詳細設計書/●詳細設計書_在庫一覧画面.xlsx
申し訳ございません。修正しました。

2024-11-19 05:25 UTC, HarukaMatano commented on docs/詳細設計書/●共通設計書_ログ.xlsx
申し訳ございません。理解が間違っておりました。
ログレベル、処理内容、処理対象についてはconstから取得するように明記しました。

2024-11-19 07:49 UTC, aoyagi96 approved these changes
LGTM
OKです！

2024-11-19 07:59 UTC, merged