DB操作①　
HarukaMatano/digital-ojt-development-cause-DroneInventorySystem pull request #7
Opened 2024-10-28 08:24 UTC by HarukaMatano

## 概要
データベースからの情報取得。

## 実装方針・詳細
CategoryInfo.java:データベースの内容に合わせたエンティティの記述変更
CategoryInfoService.java:データ情報の削除及びSQLからの情報取得。
CategoryInfoRepository.java:カテゴリ名の検索機能メソッド。

## 影響範囲
分類情報画面のみ。

2024-10-28 11:50 UTC, aoyagi96 requested changes
コメントしましたのでご確認ください。

2024-10-28 11:50 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/service/CategoryInfoService.java
> +
このリポジトリがサービス メソッド内で適切に注入され、使用されるようにするためにコンストラクタが必要になります。
lombok.RequiredArgsConstructorをインポートする事で、コンストラクタを自動生成してくれます。
（CenterInfoServiceを参照）
コンストラクタを作成するか、RequiredArgsConstructorをアノテーションするかの対応をお願いします。
https://qiita.com/supreme0110/items/391505da8f4321736421

2024-10-28 11:50 UTC, aoyagi96 commented on DroneInventorySystem/src/main/resources/application.properties
> +#spring.datasource.url=jdbc:mysql://localhost:3306/stock_mng //データベース名が異なるので変更。
もし可能であればDB名はstock_mngでお願いします。

2024-10-28 11:50 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/entity/CategoryInfo.java
> +    private LocalDateTime createDate;
Timestampのままでも良いかと思ったのですが、あえてLocalDateTime理由はありますでしょうか？

2024-10-29 00:04 UTC, HarukaMatano commented on DroneInventorySystem/src/main/java/com/digitalojt/web/entity/CategoryInfo.java
> +    private LocalDateTime createDate;
データベースと異なるデータ型であるとエラーが表示された為、変更しました。

2024-10-29 00:04 UTC, HarukaMatano commented on DroneInventorySystem/src/main/resources/application.properties
> +#spring.datasource.url=jdbc:mysql://localhost:3306/stock_mng //データベース名が異なるので変更。
変更いたしました。

2024-10-29 00:05 UTC, HarukaMatano commented on DroneInventorySystem/src/main/java/com/digitalojt/web/service/CategoryInfoService.java
> +
Line18に@RequiredArgsConstructorが記述してあるのですがこれとは異なるものでしょうか？

2024-10-29 00:13 UTC, HarukaMatano commented on DroneInventorySystem/src/main/java/com/digitalojt/web/entity/CategoryInfo.java
> +    private LocalDateTime createDate;
確認したところ、データのデータ型がdatetime(6) だったのでエラーとして表示されました。

2024-10-29 00:23 UTC, aoyagi96 approved these changes
LGTM
OKです！

2024-10-29 00:23 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/service/CategoryInfoService.java
> +
すいません、実装されてましたね。
ご存知かもしれませんが、lombokはいい感じにAnnotaitionで、javaのよく出てくる処理を書いてくれるので便利です！

2024-10-29 00:23 UTC, aoyagi96 commented on DroneInventorySystem/src/main/java/com/digitalojt/web/entity/CategoryInfo.java
> +    private LocalDateTime createDate;
承知しました！

2024-10-29 00:23 UTC, aoyagi96 commented on DroneInventorySystem/src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3306/stock_mng
ご対応ありがとうございます！

2024-10-29 00:27 UTC, merged