単体テスト（DB操作）
HarukaMatano/digital-ojt-development-cause-DroneInventorySystem pull request #9
Opened 2024-10-30 04:13 UTC by HarukaMatano

##概要
DB操作①②の単体テストを実施。

##影響範囲
分類情報管理画面
docs/試験項目書兼結果報告書

##テスト
【試験項目書】
●項番
●テスト対象
●テスト内容
●前提条件
●入力データ
●期待結果

【エビデンス】
●項番
●実行結果
●スクリーンショット
●結果の評価
- テストケース 3

2024-10-30 09:19 UTC, aoyagi96 requested changes
以下のご対応をお願いします。
- 試験報告書はMVCとDBでブックを分けるようにしてください。
- DBから取得している事がわかるエビデンスを添付してください。（DBのスクショなど）
よろしくお願いいたします。

2024-10-30 23:48 UTC, HarukaMatano commented
試験報告書を分割しました。
また、試験項目を追加しDBから取得していることが分かるスクリーンショット(DB)を添付いたしました。
よろしくお願いいたします。

2024-10-31 00:11 UTC, aoyagi96 approved these changes
確認しました。
OKです。
成果物からサンプルのシートは削除しておいてください。

2024-10-31 00:13 UTC, HarukaMatano commented
承知しました。サンプルシート削除した上でマージさせていただきます。

2024-11-06 05:59 UTC, closed without merging